In [374]:
import numpy as np
import pandas as pd

In [442]:
sam=pd.read_excel('gn\sample.xlsx')

In [443]:
sam.head()

Unnamed: 0  enb_id  cellnum enb_cell  pci  frequency    enb_pci    etl_dt  \
0           0   34288        2  34288_2  399        4.0  34288_399  20190224   
1           1   34288        1  34288_1  399        9.0  34288_399  20190224   
2           2   34288        0  34288_0  399        5.0  34288_399  20190224   
3           3   34288        3  34288_3  399        1.0  34288_399  20190224   
4           4   34288        6  34288_6  413        4.0  34288_413  20190224   

  freq_classify          bts_name  ...   cell_lat    cell_lng  mcp_nm sgg_nm  \
0   2.6GHz(10M)  SKB해운대국사_해운대좌동L0  ...  35.168056  129.179167      부산   해운대구   
1   2.6GHz(20M)  SKB해운대국사_해운대좌동L0  ...  35.200833  129.152500      부산   해운대구   
2        1.8GHz  SKB해운대국사_해운대좌동L0  ...  35.198923  129.150121      부산   해운대구   
3        800MHz  SKB해운대국사_해운대좌동L0  ...  35.198923  129.150121      부산   해운대구   
4   2.6GHz(10M)  SKB해운대국사_해운대좌동L0  ...  35.168056  129.179167      부산   해운대구   

  emd_nm freq_code  part_id    part_name freq_cnt  sigu_nm  
0     좌동         4     1101  경남/동부산품질개선팀        4   부산해운대구  
1    반여동         9     1101  경남/동부산품질개선팀        4   부산해운대구  
2    반여동         5     1101  경남/동부산품질개선팀        4   부산해운대구  
3    반여동         1     1101  경남/동부산품질개선팀        4   부산해운대구  
4     좌동         4     1101  경남/동부산품질개선팀        4   부산해운대구  

[5 rows x 21 columns]

In [444]:
sam.columns.values[0]='id1'
sam.inplace=True

In [445]:
sam.reset_index(inplace=True)

In [446]:
sam.head(1)

index  id1  enb_id  cellnum enb_cell  pci  frequency    enb_pci    etl_dt  \
0      0    0   34288        2  34288_2  399        4.0  34288_399  20190224   

  freq_classify  ...   cell_lat    cell_lng  mcp_nm  sgg_nm emd_nm freq_code  \
0   2.6GHz(10M)  ...  35.168056  129.179167      부산    해운대구     좌동         4   

  part_id    part_name  freq_cnt sigu_nm  
0    1101  경남/동부산품질개선팀         4  부산해운대구  

[1 rows x 22 columns]

In [447]:
sam=sam[['id1','enb_cell','cell_nm','cell_lat','cell_lng']]

In [448]:
sam_lat=np.array(sam['cell_lat'])

In [449]:
np.round(sam_lat,3)

array([35.168, 35.201, 35.199, 35.199, 35.168, 35.206, 35.206, 35.201,
       35.183, 35.191, 35.168, 35.186, 35.168, 35.168, 35.168, 35.168,
       35.168, 35.168, 35.168, 35.168, 35.161, 35.168, 35.173, 35.168,
       35.173, 35.226, 35.226, 35.229, 35.229, 35.226, 35.226, 35.231,
       35.231, 35.231, 35.233, 35.233, 35.214, 35.214, 35.211, 35.211,
       35.235, 35.23 , 35.229, 35.233, 35.233, 35.249, 35.249, 35.249,
       35.249, 35.249, 35.261, 35.249, 35.237, 35.237, 35.237, 35.249,
       35.249, 35.238, 35.238, 35.27 , 35.249, 35.27 , 35.27 , 35.279,
       35.249, 35.249, 35.249, 35.222, 35.222, 35.222, 35.222, 35.222,
       35.221, 35.234, 35.234, 35.249, 35.249, 35.239, 35.2  , 35.193,
       35.197, 35.201, 35.201, 35.212, 35.212, 35.212, 35.053, 35.053,
       35.053, 35.058, 35.043, 35.043, 34.994, 35.033, 35.033, 35.037,
       35.037, 35.22 , 35.22 , 35.227, 35.227, 35.227])

In [450]:
sam_lat.shape

(102,)

In [451]:
sam_lat=sam_lat.reshape(1,102)

In [452]:
sam_lat

array([[35.1680556, 35.2008333, 35.1989228, 35.1989228, 35.1680556,
        35.2058353, 35.2056789, 35.2013983, 35.1827894, 35.1907481,
        35.1680556, 35.1858758, 35.1680556, 35.1680556, 35.1680556,
        35.1680556, 35.1680556, 35.1680556, 35.1680556, 35.1680556,
        35.1608353, 35.1680556, 35.1727872, 35.1680556, 35.1728722,
        35.2263889, 35.2263889, 35.2286217, 35.2288994, 35.2264019,
        35.2263889, 35.2308008, 35.2308008, 35.2305792, 35.2325908,
        35.2325908, 35.2141742, 35.2141742, 35.2105658, 35.2105658,
        35.235    , 35.2303044, 35.2289156, 35.2325119, 35.2325119,
        35.2494444, 35.2494444, 35.2494444, 35.2494444, 35.2494444,
        35.2609839, 35.2494444, 35.23687  , 35.2368697, 35.2366869,
        35.2494444, 35.2494444, 35.2381089, 35.2381089, 35.2697228,
        35.2494444, 35.2697228, 35.2697228, 35.2788889, 35.2494447,
        35.2494447, 35.2494447, 35.2222328, 35.2222328, 35.2219608,
        35.2219608, 35.2216289, 35.2214011, 35.2

In [453]:
sam_lat2=sam_lat.reshape(102,1)

In [454]:
re=sam_lat-sam_lat2

In [455]:
np.round(re,3)

array([[ 0.   ,  0.033,  0.031, ...,  0.059,  0.059,  0.059],
       [-0.033,  0.   , -0.002, ...,  0.026,  0.026,  0.026],
       [-0.031,  0.002,  0.   , ...,  0.028,  0.028,  0.028],
       ...,
       [-0.059, -0.026, -0.028, ...,  0.   ,  0.   , -0.   ],
       [-0.059, -0.026, -0.028, ...,  0.   ,  0.   , -0.   ],
       [-0.059, -0.026, -0.028, ...,  0.   ,  0.   ,  0.   ]])

In [456]:
re_abs=np.abs(re)

In [457]:
re_abs=np.round(re_abs,3)

In [458]:
re_abs

array([[0.   , 0.033, 0.031, ..., 0.059, 0.059, 0.059],
       [0.033, 0.   , 0.002, ..., 0.026, 0.026, 0.026],
       [0.031, 0.002, 0.   , ..., 0.028, 0.028, 0.028],
       ...,
       [0.059, 0.026, 0.028, ..., 0.   , 0.   , 0.   ],
       [0.059, 0.026, 0.028, ..., 0.   , 0.   , 0.   ],
       [0.059, 0.026, 0.028, ..., 0.   , 0.   , 0.   ]])

In [459]:
out=(re_abs >0) & (re_abs <=0.002)

In [460]:
out

array([[False, False, False, ..., False, False, False],
       [False, False,  True, ..., False, False, False],
       [False,  True, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]])

In [461]:
re_abs_re=np.argwhere(out==1)

In [462]:
len(re_abs_re)

264

In [463]:
re_abs_re_pd=pd.DataFrame(re_abs_re)

In [464]:
re_abs_re_pd.columns=('id1','target')

In [465]:
re_abs_re_pd.columns

Index(['id1', 'target'], dtype='object')

In [466]:
re_abs_re_pd.head()

id1  target
0    1       2
1    1       3
2    1       7
3    1      78
4    2       1

In [434]:
# sam.head()

In [435]:
# cell_merge = pd.merge(re_abs_re_pd,sam,how='left', left_on='id',right_on='id')
# cell_merge = sam.merge(re_abs_re_pd,on='id',how='left')
# cell_merge = pd.merge(re_abs_re_pd,sam,how='left', left_on='target',right_on='id')
# sam_cell=sam[['id','enb_cell']]
# cell_merge=re_abs_re_pd.join(sam, on='id', how='left', lsuffix='_left', rsuffix='_right')
# cell_merge

In [473]:
cell_merge = pd.merge(re_abs_re_pd,sam,on='id1',how='left')
cell_merge_all = pd.merge(cell_merge,sam,left_on='target',right_on='id1',how='left')

In [475]:
cell_merge_all.head()

id1_x  target  enb_id_x      cell_nm_x  cell_lat_x  cell_lng_x  id1_y  \
0      1       2     34288  해운대장산2LRRU_F5   35.200833  129.152500      2   
1      1       3     34288  해운대장산2LRRU_F5   35.200833  129.152500      3   
2      1       7     34288  해운대장산2LRRU_F5   35.200833  129.152500      7   
3      1      78     34288  해운대장산2LRRU_F5   35.200833  129.152500     78   
4      2       1     34288    해운대장산2LRRUM   35.198923  129.150121      1   

   enb_id_y        cell_nm_y  cell_lat_y  cell_lng_y  
0     34288      해운대장산2LRRUM   35.198923  129.150121  
1     34288       해운대장산2LRRU   35.198923  129.150121  
2     34288      해운대장산4LRRUM   35.201398  129.167509  
3     41418  강서죽동그린상사LRRU_F2   35.200138  128.891667  
4     34288    해운대장산2LRRU_F5   35.200833  129.152500

## distance 로 구하기

In [506]:
sam_dis=pd.read_excel('gn\sample.xlsx')

In [507]:
sam_dis.columns.values[0]='id1'
sam_dis.inplace=True

In [508]:
sam_dis.reset_index(inplace=True)

In [509]:
sam_dis=sam_dis[['id1','enb_cell','cell_nm','cell_lat','cell_lng']]

In [511]:
t_lat=np.array(sam_dis['cell_lat'])
t_lon=np.array(sam_dis['cell_lng'])

In [512]:
sam_dis.head()

id1 enb_cell              cell_nm   cell_lat    cell_lng
0    0  34288_2  haeundaejwadongL0_2  35.168056  129.179167
1    1  34288_1        해운대장산2LRRU_F5  35.200833  129.152500
2    2  34288_0          해운대장산2LRRUM  35.198923  129.150121
3    3  34288_3           해운대장산2LRRU  35.198923  129.150121
4    4  34288_6  haeundaejwadongL0_6  35.168056  129.179167

In [513]:
len(t_lat)

102

In [514]:
t_lat1=t_lat.reshape(102,1)

In [515]:
t_lat2=t_lat.reshape(1,102)

In [516]:
d_lat=np.radians(t_lat2)-np.radians(t_lat1)

In [517]:
t_lon1=t_lon.reshape(102,1)
t_lon2=t_lon.reshape(1,102)

In [518]:
d_lon=np.radians(t_lon2)-np.radians(t_lon1)

In [519]:
a=np.sin(d_lat/2)**2+np.cos(t_lat1)*np.cos(t_lat2)*np.sin(d_lon/2)**2

In [520]:
c=2*np.arcsin(np.sqrt(a))


In [521]:
c

array([[0.00000000e+00, 6.85040717e-04, 6.77460182e-04, ...,
        1.06770427e-03, 1.06770427e-03, 1.06444566e-03],
       [6.85040717e-04, 0.00000000e+00, 4.70882893e-05, ...,
        4.70833731e-04, 4.70833731e-04, 4.66026420e-04],
       [6.77460182e-04, 4.70882893e-05, 0.00000000e+00, ...,
        5.11005421e-04, 5.11005421e-04, 5.06093584e-04],
       ...,
       [1.06770427e-03, 4.70833731e-04, 5.11005421e-04, ...,
        0.00000000e+00, 0.00000000e+00, 5.28361524e-06],
       [1.06770427e-03, 4.70833731e-04, 5.11005421e-04, ...,
        0.00000000e+00, 0.00000000e+00, 5.28361524e-06],
       [1.06444566e-03, 4.66026420e-04, 5.06093584e-04, ...,
        5.28361524e-06, 5.28361524e-06, 0.00000000e+00]])

In [ ]:
km=6371*c

In [523]:
km

array([[0.        , 4.36439441, 4.31609882, ..., 6.80234392, 6.80234392,
        6.78158329],
       [4.36439441, 0.        , 0.29999949, ..., 2.9996817 , 2.9996817 ,
        2.96905432],
       [4.31609882, 0.29999949, 0.        , ..., 3.25561554, 3.25561554,
        3.22432222],
       ...,
       [6.80234392, 2.9996817 , 3.25561554, ..., 0.        , 0.        ,
        0.03366191],
       [6.80234392, 2.9996817 , 3.25561554, ..., 0.        , 0.        ,
        0.03366191],
       [6.78158329, 2.96905432, 3.22432222, ..., 0.03366191, 0.03366191,
        0.        ]])

In [524]:
dis_pd=pd.DataFrame(km)
dis_pd.head()

0         1         2         3         4         5         6    \
0  0.000000  4.364394  4.316099  4.316099  0.000000  4.451568  4.515051   
1  4.364394  0.000000  0.299999  0.299999  4.364394  1.068839  0.875468   
2  4.316099  0.299999  0.000000  0.000000  4.316099  1.362342  1.173836   
3  4.316099  0.299999  0.000000  0.000000  4.316099  1.362342  1.173836   
4  0.000000  4.364394  4.316099  4.316099  0.000000  4.451568  4.515051   

        7         8         9    ...        92         93         94   \
0  3.853164  1.991469  2.813556  ...  38.535655  36.887877  36.887877   
1  1.336557  2.374271  1.607304  ...  38.129412  36.010161  36.010161   
2  1.572100  2.327956  1.639873  ...  37.838735  35.727954  35.727954   
3  1.572100  2.327956  1.639873  ...  37.838735  35.727954  35.727954   
4  3.853164  1.991469  2.813556  ...  38.535655  36.887877  36.887877   

         95         96        97        98        99        100       101  
0  37.663424  37.663424  6.276808  6.276808  6.802344  6.802344  6.781583  
1  36.667855  36.667855  2.162130  2.162130  2.999682  2.999682  2.969054  
2  36.388560  36.388560  2.383858  2.383858  3.255616  3.255616  3.224322  
3  36.388560  36.388560  2.383858  2.383858  3.255616  3.255616  3.224322  
4  37.663424  37.663424  6.276808  6.276808  6.802344  6.802344  6.781583  

[5 rows x 102 columns]

In [532]:
# dis_pd.columns.values[0]='id1'
dis_pd.reset_index(inplace=True)

In [533]:
dis_pd.head()

index         0         1         2         3         4         5  \
0      0  0.000000  4.364394  4.316099  4.316099  0.000000  4.451568   
1      1  4.364394  0.000000  0.299999  0.299999  4.364394  1.068839   
2      2  4.316099  0.299999  0.000000  0.000000  4.316099  1.362342   
3      3  4.316099  0.299999  0.000000  0.000000  4.316099  1.362342   
4      4  0.000000  4.364394  4.316099  4.316099  0.000000  4.451568   

          6         7         8  ...         92         93         94  \
0  4.515051  3.853164  1.991469  ...  38.535655  36.887877  36.887877   
1  0.875468  1.336557  2.374271  ...  38.129412  36.010161  36.010161   
2  1.173836  1.572100  2.327956  ...  37.838735  35.727954  35.727954   
3  1.173836  1.572100  2.327956  ...  37.838735  35.727954  35.727954   
4  4.515051  3.853164  1.991469  ...  38.535655  36.887877  36.887877   

          95         96        97        98        99       100       101  
0  37.663424  37.663424  6.276808  6.276808  6.802344  6.802344  6.781583  
1  36.667855  36.667855  2.162130  2.162130  2.999682  2.999682  2.969054  
2  36.388560  36.388560  2.383858  2.383858  3.255616  3.255616  3.224322  
3  36.388560  36.388560  2.383858  2.383858  3.255616  3.255616  3.224322  
4  37.663424  37.663424  6.276808  6.276808  6.802344  6.802344  6.781583  

[5 rows x 103 columns]

In [608]:
x = np.arange(12).reshape((3, 4))
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [610]:
row_idx = np.array([0, 1, 2])
row_idx

array([0, 1, 2])

In [611]:
col_idx = np.array([2, 1, 3])
col_idx

array([2, 1, 3])

In [616]:
km[row_idx, col_idx]

array([4.31609882, 0.        , 0.        ])

In [617]:
km[0,1]

4.364394407284501

In [624]:
dis_pd[dis_pd[0]>5].index.values

array([ 25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,
        38,  39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,
        51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,
        64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,
        77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,
        90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101],
      dtype=int64)

In [629]:
dis_pd.loc[0,1]

4.364394407284501

In [591]:
idx=np.array([3,7,1])
km[idx]

array([[ 4.31609882,  0.29999949,  0.        ,  0.        ,  4.31609882,
         1.36234232,  1.17383636,  1.5721001 ,  2.32795636,  1.63987283,
         4.31609882,  1.8766706 ,  4.31609882,  4.31609882,  4.31609882,
         4.31609882,  4.31609882,  4.31609882,  4.31609882,  4.31609882,
         4.491119  ,  4.31609882,  3.2541936 ,  4.31609882,  3.24990524,
        22.21272772, 22.26124543, 22.85813341, 22.88435268, 22.25992564,
        22.21272772, 22.229976  , 22.229976  , 22.22065761, 22.91126013,
        22.91126013, 21.0420764 , 21.0420764 , 21.31310568, 21.31310568,
        22.05029771, 21.56567736, 21.55284867, 21.68484648, 21.68484648,
        24.93739269, 24.93739269, 24.93739269, 24.93739269, 24.93739269,
        25.83592432, 24.93739269, 25.87816813, 25.87826102, 25.88704547,
        24.93739269, 24.93739269, 25.49897815, 25.49897815, 26.28058076,
        24.93739269, 26.28058076, 26.28058076, 26.62371761, 24.93737174,
        24.93737174, 24.93737174, 25.06472837, 25.0

In [599]:
zzz=np.random.randint(0,7,(3,5,2))

In [600]:
zzz

array([[[4, 5],
        [4, 5],
        [6, 4],
        [5, 6],
        [6, 6]],

       [[1, 2],
        [2, 5],
        [4, 0],
        [4, 0],
        [4, 3]],

       [[5, 1],
        [2, 4],
        [6, 5],
        [2, 2],
        [0, 3]]])

In [601]:
zzz[1]

array([[1, 2],
       [2, 5],
       [4, 0],
       [4, 0],
       [4, 3]])

In [578]:
name2 = ['Alice', 'Bob', 'Cathy', 'Doug']
age = [25, 45, 37, 19]

In [539]:
name = ['Alice', 'Bob', 'Cathy', 'Doug']
age = [25, 45, 37, 19]
weight = [55.0, 85.5, 68.0, 61.5]

In [540]:
data = np.zeros(4, dtype = {'names':('name', 'age', 'weight'),
                        'formats':('U10', 'i4', 'f8')})

data

array([('', 0, 0.), ('', 0, 0.), ('', 0, 0.), ('', 0, 0.)],
      dtype=[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')])

In [541]:
data['name'] = name
data['age'] = age
data['weight'] = weight

data

array([('Alice', 25, 55. ), ('Bob', 45, 85.5), ('Cathy', 37, 68. ),
       ('Doug', 19, 61.5)],
      dtype=[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')])

In [542]:
np.array(data['age'])

array([25, 45, 37, 19])

In [543]:
data['age']

array([25, 45, 37, 19])

In [545]:
np.array(data['weight'])

array([55. , 85.5, 68. , 61.5])

In [562]:
data['age'].reshape(1,4)

array([[25, 45, 37, 19]])

In [553]:
rt=data['weight'].reshape(4,1)

In [552]:
rt=data['weight']

array([55. , 85.5, 68. , 61.5])

In [554]:
rt

array([[55. ],
       [85.5],
       [68. ],
       [61.5]])

In [557]:
bb=data['age']*rt

In [581]:
data22=np.array(bb,dtype={'names':('name2')})

ValueError: entry not a 2- or 3- tuple

In [571]:
data2=np.zeros(4,dtype={'ons':('name','age','weight'),
                           'formats':('U10', 'i4', 'f8')})

ValueError: invalid literal for int() with base 10: 'age'

In [567]:
data2

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [ ]:
sam_cell_re_pd.to_csv('sam_cell_re_pd',encoding='Euc-kr')

In [ ]:
re_abs_re=np.all(re_abs<=0.002,axis=1)

In [37]:
re_abs

array([[0.   , 0.033, 0.031, ..., 0.059, 0.059, 0.059],
       [0.033, 0.   , 0.002, ..., 0.026, 0.026, 0.026],
       [0.031, 0.002, 0.   , ..., 0.028, 0.028, 0.028],
       ...,
       [0.059, 0.026, 0.028, ..., 0.   , 0.   , 0.   ],
       [0.059, 0.026, 0.028, ..., 0.   , 0.   , 0.   ],
       [0.059, 0.026, 0.028, ..., 0.   , 0.   , 0.   ]])

In [24]:
re_abs_re

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False])

In [46]:
# np.argsort : 정렬된 요소의 인덱스 반환

re_abs_re=np.where(re_abs<0.002,axis=1) 

TypeError: where() takes no keyword arguments

In [18]:
re_abs_re

(array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          1,   1,   1,   1,   1,   2,   2,   2,   2,   3,   3,   3,   3,
          4,   4,   4,   4,   4,   4,   4,   4,   4,   4,   4,   4,   4,
          5,   5,   6,   6,   7,   7,   7,   7,   7,   8,   9,  10,  10,
         10,  10,  10,  10,  10,  10,  10,  10,  10,  10,  10,  11,  12,
         12,  12,  12,  12,  12,  12,  12,  12,  12,  12,  12,  12,  13,
         13,  13,  13,  13,  13,  13,  13,  13,  13,  13,  13,  13,  14,
         14,  14,  14,  14,  14,  14,  14,  14,  14,  14,  14,  14,  15,
         15,  15,  15,  15,  15,  15,  15,  15,  15,  15,  15,  15,  16,
         16,  16,  16,  16,  16,  16,  16,  16,  16,  16,  16,  16,  17,
         17,  17,  17,  17,  17,  17,  17,  17,  17,  17,  17,  17,  18,
         18,  18,  18,  18,  18,  18,  18,  18,  18,  18,  18,  18,  19,
         19,  19,  19,  19,  19,  19,  19,  19,  19,  19,  19,  19,  20,
         21,  21,  21,  21,  21,  21,  21,  21,  21