> Quiz 1 : 맨 가장자리는 모두 0, 내부는 모두 1인 10 by 10 행렬을 구하여라.

In [4]:
import numpy as np
x=np.array([0,1,1,1,1,1,1,1,1,0])

In [11]:
xx=x.reshape(1,10)

In [13]:
xx*xx.T

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

> Quiz 2 : 행렬 A, B에 대하여 $((A+B)\times(-A/2))$를 in place (without copy)로 계산하여라.

In [31]:
A=np.array([1,2,3])
B=np.array([4,5,6])

In [37]:
r1=A+B
r2=(-1*A)/2
r1*r2

array([ -2.5,  -7. , -13.5])

> Quiz 3:
- 3개의 배열이 주어졌을 때, 아래의 조건에 따라 새롭게 생성되는 배열을 구하시오
 - `cond[i]`가 `true`이면, `xarr[i]`를 선택
 - `cond[i]`가 `false`이면, `yarr[i]`를 선택
 
```python
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])```

In [42]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

In [43]:
np.where(cond,xarr,yarr)

array([1.1, 2.2, 1.3, 1.4, 2.5])

> Quiz 4 : 크기가 11인 배열이 다음과 같이 주어졌을 때, 5번째 원소부터 9번째 원소까지를 음수로 바꾸어 보시오.
- `quiz4Arr = np.arange(11)`

In [67]:
quiz4Arr = np.arange(11)
quiz4Arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [68]:
arr=quiz4Arr[5:10]
quiz4Arr[arr] *=-1
quiz4Arr

array([ 0,  1,  2,  3,  4, -5, -6, -7, -8, -9, 10])

> Quiz 5 : 난수생성기를 사용하여 크기가 0부터 9까지의 숫자로 구성된, 크기가 20인 배열을 생성하고, 배열의 최대값을 0으로 만들어라.

In [98]:
z = np.random.randint(10, size = (20))
z

array([5, 5, 9, 5, 9, 1, 3, 4, 9, 5, 4, 6, 0, 2, 4, 6, 3, 9, 0, 7])

In [99]:
imax=z.max()
ind=np.argwhere(z==imax)
ind

array([[ 2],
       [ 4],
       [ 8],
       [17]], dtype=int64)

In [100]:
z[ind]*=0

In [101]:
z

array([5, 5, 0, 5, 0, 1, 3, 4, 0, 5, 4, 6, 0, 2, 4, 6, 3, 0, 0, 7])